name: hightable_mobile_v2
description: Hightable Mobile App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3

  #dependency injector
  get_it: ^7.2.0

  #Network and API
  cached_network_image: ^3.2.0 

  # utils
  validators: ^3.0.0
  flutter_svg: ^0.22.0

  #animation
  supercharged: ^2.1.1
  simple_animations: ^4.0.1

  #UI
  glassmorphism_ui: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

  #DB
  hive: ^2.1.0
  hive_flutter: ^1.1.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/

